// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID          string         `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	Description string         `gorm:"column:description;type:text;not null" json:"description"`
	State       string         `gorm:"column:state;type:text;not null" json:"state"`
	CreatedBy   string         `gorm:"column:created_by;type:varchar(36);not null" json:"created_by"`
	CreatedAt   *time.Time     `gorm:"column:created_at;type:datetime;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
